dist: trusty

language: python
python:
  - "2.7"
  - "3.6"

env:
  fast_finish: true


install:
  - pip install -e .
  - pip install pycodestyle
  # - pip install -r extra_test_requirements.txt

  - 'if [ -n "$GOOGLE_CREDENTIALS_ENCODED" ]; then echo "$GOOGLE_CREDENTIALS_ENCODED" | base64 --decode > ./credentials.json && export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/credentials.json; fi'

script:
  - echo $GOOGLE_APPLICATION_CREDENTIALS
  - nosetests -v --processes=16 --process-timeout=590
  - pycodestyle --show-source .
  - python setup.py sdist

deploy:
  provider: pypi
  distributions: "sdist"
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true


jobs:
    include: 
    - stage: test_docker
      #sudo: required
      #services: 
      #  - docker

      #env: 
      #  - TEST_DOCKER=true

      #python: 
      #  - "2.7"
      #  - "3.6"

      #before_install:
      #  - docker pull peterzhokhoff/studioml
        
      script: cd studio/tests && nosetests -v remote_worker_test --processes=16 --process-timeout=590

 
